# common
spring.application.name=notifier
server.port=8009

# mail
spring.mail.protocol=smtps
spring.mail.port=465
spring.mail.host=smtp.yandex.ru
spring.mail.username=i@kovalkov-andrey.ru
spring.mail.password=njopjelsweqhjafq
