version: '3.9'
services:
  db:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: service_user
      POSTGRES_PASSWORD: service_password
      POSTGRES_DB: service
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080